/* 销售合同 */
DROP TABLE IF EXISTS `contract_sales`;
CREATE TABLE `contract_sales` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `project_name` varchar(120) NOT NULL COMMENT '工程名称',
  `contract_id` varchar(32) DEFAULT NULL COMMENT '合同编号',
  `contract_date` varchar(20) DEFAULT NULL COMMENT '签定日期',
  `contract_comp` varchar(120) DEFAULT NULL COMMENT '合同单位',
  `project_addr` varchar(240) DEFAULT NULL COMMENT '项目地址',
  `contract_department` varchar(60) DEFAULT NULL COMMENT '签定部门',
  `sales_person` varchar(60) DEFAULT NULL COMMENT '业务员',
  `comstem_type` varchar(32) DEFAULT NULL COMMENT '客户分类',
  `tong_accmeth` varchar(60) DEFAULT NULL COMMENT '砼结算方式',
  `contract_addr` varchar(240) DEFAULT NULL COMMENT '签定地点',
  `third_person` varchar(60) DEFAULT NULL COMMENT '见证方',
  `eff_term` varchar(1) DEFAULT NULL COMMENT '有效期限',
  `eff_start` varchar(20) DEFAULT NULL COMMENT '起始期限',
  `eff_end` varchar(20) DEFAULT NULL COMMENT '终止期限',
  `cube_control` varchar(1) DEFAULT NULL COMMENT '方量控制',
  `cube_start` varchar(32) DEFAULT NULL COMMENT '起始方量',
  `cube_end` varchar(32) DEFAULT NULL COMMENT '终止方量',
  `time_control` varchar(1) DEFAULT NULL COMMENT '时间控制',
  `time_start` varchar(20) DEFAULT NULL COMMENT '起始时间',
  `time_end` varchar(20) DEFAULT NULL COMMENT '终止时间',
  `create_person` varchar(60) DEFAULT NULL COMMENT '制单人',
  `check_person` varchar(60) DEFAULT NULL COMMENT '审核人',
  `cancle_person` varchar(60) DEFAULT NULL COMMENT '作废人',
  `create_date` varchar(20) DEFAULT NULL COMMENT '制单日期',
  `check_date` varchar(20) DEFAULT NULL COMMENT '审核日期',
  `cancel_date` varchar(20) DEFAULT NULL COMMENT '作废日期',
  `contract_remark` varchar(256) DEFAULT NULL COMMENT '备注',
  `concrete_price` varchar(11) DEFAULT NULL COMMENT '混凝土单价',
  `watermeth_price` varchar(11) DEFAULT NULL COMMENT '浇灌方式单价',
  `spec_price` varchar(11) DEFAULT NULL COMMENT '特殊要求单价',
  `sum_control` varchar(1000) DEFAULT NULL COMMENT '其它特殊要求',
  `save_inventory` varchar(1000) DEFAULT NULL COMMENT '工程需用量',
  `stock_stand` varchar(1000) DEFAULT NULL COMMENT '验收方法及期限',
  `abc_category` varchar(1000) DEFAULT NULL COMMENT '交货时间及地点',
  `tax_rate` varchar(1000) DEFAULT NULL COMMENT '结算方式',
  `quality_manage` varchar(1000) DEFAULT NULL COMMENT '付款方式',
  `ext_field1` varchar(60) DEFAULT NULL COMMENT 'ext_field1',
  `ext_field2` varchar(60) DEFAULT NULL COMMENT 'ext_field2',
  `ext_field3` varchar(120) DEFAULT NULL COMMENT 'ext_field3',
  `remark` varchar(1000) DEFAULT NULL COMMENT 'remark',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '销售合同';
